### Buscar todo os ID
GET http://localhost:3333/user

### Buscar ID especifico
GET http://localhost:3333/user

### Buscar ID especifico
GET http://localhost:3333/user

### Inserir Informação no banco
POST http://localhost:3333/user
content-type: application/json

{
    "id": "24251627202",
    "name": "Rafael",
    "email":"fema@fema.com",
}

### Deletar um usuario do banco
DELETE  http://localhost:3333/user
